In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
#Preprocessing data, one Hot to convert string to numeric on Gender, then rename
dataset = pd.get_dummies(dataset, drop_first=True)
dataset = dataset.rename(columns = {'Gender_Male': 'Gender'})
dataset

User ID  Age  EstimatedSalary  Purchased  Gender
0    15624510   19            19000          0       1
1    15810944   35            20000          0       1
2    15668575   26            43000          0       0
3    15603246   27            57000          0       0
4    15804002   19            76000          0       1
..        ...  ...              ...        ...     ...
395  15691863   46            41000          1       0
396  15706071   51            23000          1       1
397  15654296   50            20000          1       0
398  15755018   36            33000          0       1
399  15594041   49            36000          1       0

[400 rows x 5 columns]

In [3]:
y = dataset['Purchased'].values

In [4]:
x = dataset[['Age','EstimatedSalary','Gender']].values

In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(280, 3)
(280,)
(120, 3)
(120,)


In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train)
print(x_test)

[[ 4.68359482e-02  1.14942217e+00 -1.00000000e+00]
 [-1.38901064e+00 -1.43449573e+00  1.00000000e+00]
 [-3.36056475e-01  1.23368037e+00  1.00000000e+00]
 [-1.00611821e+00 -4.79569545e-01 -1.00000000e+00]
 [ 4.29728371e-01  1.03707792e+00 -1.00000000e+00]
 [-5.27502686e-01  8.12389405e-01  1.00000000e+00]
 [ 1.09979011e+00 -9.85118699e-01 -1.00000000e+00]
 [-1.44610263e-01  1.10237802e-01 -1.00000000e+00]
 [-5.27502686e-01  1.28985249e+00 -1.00000000e+00]
 [-1.10184132e+00  2.78754186e-01  1.00000000e+00]
 [-2.40333369e-01  7.28131212e-01 -1.00000000e+00]
 [ 1.86557496e+00  1.43028282e+00 -1.00000000e+00]
 [-4.88871576e-02 -3.95311353e-01 -1.00000000e+00]
 [-7.18948898e-01  4.47270571e-01  1.00000000e+00]
 [ 1.09979011e+00 -1.20980721e+00  1.00000000e+00]
 [-2.40333369e-01 -1.37832360e+00  1.00000000e+00]
 [-2.40333369e-01 -1.23789328e+00  1.00000000e+00]
 [-4.88871576e-02  1.10237802e-01  1.00000000e+00]
 [-1.00611821e+00 -1.12554902e+00 -1.00000000e+00]
 [ 1.19551322e+00 -7.60430186e-

In [8]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
# create logistic regression model
model = LogisticRegression()
# train the model with data
model.fit(x_train, y_train)

LogisticRegression()

In [9]:
model.coef_

array([[2.14969399, 1.11626759, 0.24494535]])

In [10]:
model.intercept_

array([-1.14795317])

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1], dtype=int64)

In [12]:
confusion_matrix(y_test, y_pred)

array([[72,  3],
       [17, 28]], dtype=int64)

In [13]:
# Correct Predictions - 45 + 22
# Wrong Prediction - 4 + 9
accuracy_score(y_test, y_pred)

0.8333333333333334

In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.96      0.88        75
           1       0.90      0.62      0.74        45

    accuracy                           0.83       120
   macro avg       0.86      0.79      0.81       120
weighted avg       0.84      0.83      0.83       120



In [15]:
# Support Vector, linear hyperplane to classify data, or non-linear, or a trick is convert data from 2 to 3 dimensional space 
from sklearn import svm
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#create support vector machine model
model1 = svm.SVC(kernel='linear')
#train the model with data
model1.fit(x_train, y_train)
#predict with test input data
y1_pred = model1.predict(x_test)

In [16]:
confusion_matrix(y_test, y1_pred)

array([[72,  3],
       [18, 27]], dtype=int64)

In [17]:
accuracy_score(y_test, y1_pred)

0.825

In [18]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.96      0.88        75
           1       0.90      0.62      0.74        45

    accuracy                           0.83       120
   macro avg       0.86      0.79      0.81       120
weighted avg       0.84      0.83      0.83       120



In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='gini',
                                   random_state=100,
                                   max_depth=3, 
                                   min_samples_leaf=3)
classifier.fit(x_train, y_train)

In [ ]:
y_pred1 = classifier.predict(x_test)
y_pred1

In [ ]:
y_predict = classifier.predict([[0.3 ,  -0.7, 1]])
y_predict

In [ ]:
accuracy_score(y_test, y_pred1)

In [ ]:
x_test